/*
 * Subscription Manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package workspaceEngine

type APlan struct {

	Code int32 `json:"code,omitempty"`

	Message string `json:"message,omitempty"`
}
