/*
 * Subscription Manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package workspaceEngine

type ListOfAPlans struct {

	Plans []APlan `json:"plans,omitempty"`
}
